# Generated by Django 4.2 on 2025-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0008_alter_convenio_nit_alter_convenio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='nit',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nit',), name='unique_nit_activo'),
        ),
    ]
